### ISSUE TITLE
The result Instruction of DRIVE is incorrect.

### ISSUE THREAD

**Issue by ZijinZheng** [ZijinZheng/iRobotGUI#10]
When I change the steering wheel to the left in DRIVE window and refresh the program, the parameter is incorrect.

Beside, turn left should generate positive value, according to Open API.

**Comment by fastboatster** [comment]
fixed problem with negative radii, turned out to be a textbox validation issue. will change rotation radius sign soon

**Comment by fastboatster** [comment]
everything fixed, and tooltips added to sliders

**Comment by ZijinZheng** [comment]
Great, it has been merged.

**Comment by ZijinZheng** [comment]
There is still a bug. When you click the steering wheel, it will move upward.

**Comment by fastboatster** [comment]
it has to do with image size and rotation center
