### ISSUE TITLE
Navi refinement

### ISSUE THREAD

**Issue by ZijinZheng** [ZijinZheng/iRobotGUI#14]
@fastboatster , refine the Navi UI as we talked: 

* Use data binding to display the value of sliders. 

* Remove the tool tip. Change the unit of move to cm. 

* Make other improvement whenever you think is necessary.

**Comment by ZijinZheng** [comment]
Add three button to Steering Wheel. 

* Turn left

* Turn right

* Straight

**Comment by fastboatster** [comment]
can't display slider values inside their thumbs, as we use custom thumb images. slider value inside an image will look very bad

**Comment by ZijinZheng** [comment]
Just a label next to the slider will be fine.

**Comment by fastboatster** [comment]
OK
